export const login = {
  CLEAR_LOGIN: "CLEAR_LOGIN",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCEESS: "LOGIN_SUCEESS",
  LOGIN_FAILD: "LOGIN_FAILD",
};
export const signup = {
  CLEAR_SIGNUP: "CLEAR_SIGNUP",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCEESS: "SIGNUP_SUCEESS",
  SIGNUP_FAILD: "SIGNUP_FAILD",
};
export const authenticate = {
  CLEAR_AUTHENTICATION: "CLEAR_AUTHENTICATION",
  AUTHENTICATION_START: "AUTHENTICATION_START",
  AUTHENTICATION_SUCEESS: "AUTHENTICATION_SUCEESS",
  AUTHENTICATION_FAILD: "AUTHENTICATION_FAILD",
};
export const createPost = {
  CLEAR_POST_CREATE: "CLEAR_POST_CREATE",
  POST_CREATE_START: "POST_CREATE_START",
  POST_CREATE_SUCEESS: "POST_CREATE_SUCEESS",
  POST_CREATE_FAILD: "POST_CREATE_FAILD",
};
export const deletePost = {
  CLEAR_POST_DELETE: "CLEAR_POST_DELETE",
  POST_DELETE_START: "POST_DELETE_START",
  POST_DELETE_SUCEESS: "POST_DELETE_SUCEESS",
  POST_DELETE_FAILD: "POST_DELETE_FAILD",
};

export const getFeed = {
  CLEAR_FEED: "CLEAR_FEED",
  GET_FEED_START: "GET_FEED_START",
  GET_FEED_SUCCESS: "GET_FEED_SUCCESS",
  GET_FEED_FAILD: "GET_FEED_FAILD",
};
export const getUser = {
  CLEAR_USER: "CLEAR_USER",
  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILD: "GET_USER_FAILD",
};

export const getPost = {
  CLEAR_POST: "CLEAR_POST",
  GET_POST_START: "GET_POST_START",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILD: "GET_POST_FAILD",
};

export const logout = {
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILD: "LOGOUT_FAILD",
};

export const getRecommendation = {
  CLEAR_RECOMMENDATION: "CLEAR_RECOMMENDATION",
  GET_RECOMMENDATION_START: "GET_RECOMMENDATION_START",
  GET_RECOMMENDATION_SUCCESS: "GET_RECOMMENDATION_SUCCESS",
  GET_RECOMMENDATION_FAILD: "GET_RECOMMENDATION_FAILD",
};

export const follow = {
  CLEAR_FOLLOW: "CLEAR_FOLLOW",
  GET_FOLLOW_START: "GET_FOLLOW_START",
  GET_FOLLOW_SUCCESS: "GET_FOLLOW_SUCCESS",
  GET_FOLLOW_FAILD: "GET_FOLLOW_FAILD",
};

export const addComment = {
  CLEAR_ADD_COMMENT: "CLEAR_ADD_COMMENT",
  ADD_COMMENT_START: "ADD_COMMENT_START",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILD: "ADD_COMMENT_FAILD",
};

export const getComment = {
  CLEAR_GET_COMMENT: "CLEAR_GET_COMMENT",
  GET_COMMENT_START: "GET_COMMENT_START",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAILD: "GET_COMMENT_FAILD",
};
